spring.application.name=userDetails

# Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=user-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.value-deserializer=com.suyash.userDetails.deserializer.UserInfoDeserializer

# Topic
kafka.topic.name=auth.user-registered

# MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/user_db
spring.datasource.username=root
spring.datasource.password=root

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082